# Tensor Creation

Create the following tensors:
1.	A scalar tensor (0D tensor).
2.	A vector with 5 elements (1D tensor).
3.	A 3x3 matrix (2D tensor).
4.	A 3x3x3 tensor (3D tensor).

For each tensor, check:
-	Its dimensions using tensor.ndim.
-	Its shape using tensor.shape.

In [2]:
import torch

def print_dimensions_shape(tensor: torch.Tensor):
    print(f"Dimensions: {tensor.dim()}")
    print(f"Shape: {tensor.shape}")

scalar = torch.tensor(7)
print_dimensions_shape(scalar)

Dimensions: 0
Shape: torch.Size([])


In [5]:
# A vector with 5 elements (1D tensor).
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print_dimensions_shape(tensor_1d)

Dimensions: 1
Shape: torch.Size([5])


In [ ]:
# A 3x3 matrix (2D tensor).
tensor_2d = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print_dimensions_shape(tensor_2d)

Dimensions: 2
Shape: torch.Size([3, 3])


In [6]:
# A 3x3x3 tensor (3D tensor).
tensor_3d = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
print_dimensions_shape(tensor_3d)

Dimensions: 3
Shape: torch.Size([3, 3, 3])


# Random Tensors

Generate random tensors of shapes:
1.	 `(3, 4)`
2.	 `(224, 224, 3)`

Verify the type of the generated tensors using tensor.dtype.

In [8]:
rand_tensor_01 = torch.rand(3,4)
print(rand_tensor_01, rand_tensor_01.dtype)

tensor([[0.5359, 0.0340, 0.7598, 0.6404],
        [0.9675, 0.0442, 0.2316, 0.7177],
        [0.4320, 0.8971, 0.6820, 0.7383]]) torch.float32


In [9]:
rand_tensor_02 = torch.rand(224,224,3)
print(rand_tensor_02, rand_tensor_02.dtype)

tensor([[[0.3267, 0.9117, 0.8975],
         [0.2945, 0.5832, 0.4966],
         [0.2364, 0.0696, 0.4399],
         ...,
         [0.5820, 0.2406, 0.7868],
         [0.2446, 0.8011, 0.2733],
         [0.1926, 0.1580, 0.0121]],

        [[0.5797, 0.8868, 0.6550],
         [0.0574, 0.5608, 0.2466],
         [0.1609, 0.5587, 0.4399],
         ...,
         [0.3891, 0.9488, 0.8673],
         [0.7282, 0.8732, 0.0830],
         [0.4236, 0.0226, 0.5316]],

        [[0.0201, 0.4071, 0.0514],
         [0.1108, 0.4866, 0.2600],
         [0.6904, 0.1331, 0.9540],
         ...,
         [0.2558, 0.7359, 0.6769],
         [0.8337, 0.5537, 0.3177],
         [0.4782, 0.8042, 0.1978]],

        ...,

        [[0.3608, 0.0110, 0.0411],
         [0.0427, 0.2522, 0.4622],
         [0.2775, 0.0825, 0.7870],
         ...,
         [0.1544, 0.2224, 0.8733],
         [0.0039, 0.4818, 0.1606],
         [0.0130, 0.8343, 0.3502]],

        [[0.9667, 0.8178, 0.9226],
         [0.6231, 0.5043, 0.6602],
         [0.

# Reshaping tensors
Create a 1D tensor with 10 elements.

Reshape it into the following shapes:
1.	 (2, 5) 
2.	 (5, 2) 
3.	 (1, 10) 

Experiment with `torch.reshape` and `torch.view` and observe any differences.

In [15]:
x = torch.rand(10)
print(f"x.shape: {x.shape}, dimension: {x.dim()}")

x.shape: torch.Size([10]), dimension: 1


In [19]:
# Reshaping the tensor
x_reshaped = x.reshape(2,5)
print_dimensions_shape(x_reshaped)
x_reshaped = x.reshape(2,5)
print_dimensions_shape(x_reshaped)
x_reshaped = x.reshape(1,10)
print_dimensions_shape(x_reshaped)

Dimensions: 2
Shape: torch.Size([2, 5])
Dimensions: 2
Shape: torch.Size([2, 5])
Dimensions: 2
Shape: torch.Size([1, 10])


# Tensor Operations

Perform the following operations on tensors:
1.	Element-wise addition, subtraction, multiplication, and division.
2.	Matrix multiplication between  (2, 3)  and  (3, 2) .
3.	Experiment with torch.matmul() and @.

In [25]:
A = torch.rand(3,3)
B = torch.rand(3,1)  # 3x1 matrix - pytorch will perform broadcasting

print(f"A + B: {A + B}")
print(f"A - B: {A - B}")
print(f"A * B: {A * B}")
print(f"A / B: {A / B}")


A + B: tensor([[1.3981, 1.3375, 1.2092],
        [1.2255, 0.8985, 1.3080],
        [0.8184, 1.0749, 0.6530]])
A - B: tensor([[ 0.0425, -0.0182, -0.1465],
        [-0.3774, -0.7044, -0.2949],
        [ 0.4807,  0.7372,  0.3153]])
A * B: tensor([[0.4882, 0.4471, 0.3602],
        [0.3398, 0.0777, 0.4060],
        [0.1097, 0.1530, 0.0817]])
A / B: tensor([[1.0627, 0.9731, 0.7839],
        [0.5291, 0.1210, 0.6321],
        [3.8465, 5.3658, 2.8672]])


In [28]:
A = torch.rand(2,3)
B = torch.rand(3,2)
print(f"matrix multiplication with mm: {A.mm(B)}")  # Matrix multiplication
print(f"matrix multiplication with torch.matmul: {torch.matmul(A, B)}")  # Matrix multiplication
print(f"matrix multiplication with @: {A@B}")  # Matrix multiplication


matrix multiplication with mm: tensor([[0.9228, 0.4964],
        [1.9032, 1.0685]])
matrix multiplication with torch.matmul: tensor([[0.9228, 0.4964],
        [1.9032, 1.0685]])
matrix multiplication with @: tensor([[0.9228, 0.4964],
        [1.9032, 1.0685]])


# Aggregation
Create a tensor with values from 0 to 10.

Compute:
-	The minimum and maximum values using torch.min and torch.max.
-	The mean using torch.mean.
-	The sum using torch.sum.

In [38]:
tensor = torch.arange(0,10,1,dtype=torch.float32)
print(tensor)
min = tensor.min()
max = tensor.max()
mean = tensor.mean()
sum = tensor.sum()

print(f"Min: {min}, Max: {max}, Mean: {mean}, sum: {sum}")

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Min: 0.0, Max: 9.0, Mean: 4.5, sum: 45.0


# Broadcasting

- Create two tensors of shapes  (1, 3)  and  (3, 3) .
- Perform addition and multiplication to observe how broadcasting works.
- Try incompatible shapes and understand the error messages.

In [43]:
A = torch.rand(1,3)
B = torch.rand(3,3)
mult = A@B
add = A+B

In [ ]:
A = torch.rand(2,3)
B = torch.rand(3,3)

# below commands won't work becase broadcasting cannot be performed on A (2,3).count
# We meed that at least one of the dimensions should be 1
# mult = A@B
# add = A+B

# Indexing and Slicing
Create a 3D tensor of shape  `(2, 3, 4)`

Extract:
-	The first element from the first dimension.
-	All elements from the second dimension of the first matrix.
-	Specific rows/columns using slicing.

In [47]:
# Create a 3D tensor of shape  `(2, 3, 4)`
tensor = torch.rand(2,3,4)
tensor

tensor([[[0.0937, 0.6178, 0.1607, 0.2434],
         [0.9296, 0.9087, 0.2702, 0.4704],
         [0.5306, 0.2259, 0.2698, 0.0491]],

        [[0.1198, 0.8794, 0.8197, 0.2906],
         [0.4027, 0.7403, 0.3663, 0.9733],
         [0.1229, 0.5125, 0.0064, 0.2798]]])

In [50]:
# First element of the first dimension
tensor[0]

tensor([[0.0937, 0.6178, 0.1607, 0.2434],
        [0.9296, 0.9087, 0.2702, 0.4704],
        [0.5306, 0.2259, 0.2698, 0.0491]])

In [53]:
# All elements from the second dimension of the first matrix.
print(tensor[0,:, 1])
print(tensor[0,1, :])

tensor([0.6178, 0.9087, 0.2259])
tensor([0.9296, 0.9087, 0.2702, 0.4704])
